#!/usr/bin/env python3
import sys
import hashlib
import os
import shutil
from re import sub
from time import strftime

def main():
    archive = os.path.expanduser("~/archive")
    index_file = archive + "/index.csv"
    if len(sys.argv) != 2 and len(sys.argv) != 3:
        print("usage: a file [\"comment\"]")
        sys.exit(2)
    if len(sys.argv) > 1:
        file = sys.argv[1]
        if not os.path.isfile(file):
            print("file %s does not exist" % file)
            sys.exit(2)
        file_name, file_extension = os.path.splitext(file)
        if (len(sys.argv) == 3):
            comment = sys.argv[2]
        else:
            comment = ""
        path = os.getcwd() + "/" + file
        path_tilde = sub(os.path.expanduser("~"), "~", path)
        hash = str(hashlib.sha1(str(path).encode('utf-8')).hexdigest())[:6]
        destination = os.path.expanduser(archive + "/" + str(hash) + file_extension)
        print("Original File:    %s" % path)
        print("Destination File: %s" % destination)
        print("Index File:       %s" % index_file)
        print("Comment:          %s" % comment)
        destination_file = sub(".*/", "", destination)
        time = strftime("%Y-%m-%dT%H:%M:%S")
        msg = destination_file + "," + path_tilde + "," + time + "," + comment
        shutil.copy(path, destination)
        # Create the index file, if it does not exist already.
        if not os.path.exists(index_file):
            f = open(index_file, "w")
            f.write("File Name,Original File Name,Archive Time,Comment\n")
            f.close()
            print("-- Created %s and added a header line to it." % index_file)
        # Append or update index
        index_file_new = index_file + "-new"
        fnew = open(index_file_new, "w")
        replaced = False
        with open(index_file, "r") as f:
            for line in f:
                # FIXME: better to just check the first comma-separated item
                if destination_file in line:
                    fnew.write(msg + '\n')
                    replaced = True
                    print("-- updating existing index entry")
                else:
                    fnew.write(line)
        if not replaced:
            print("-- adding existing index entry")
            fnew.write(msg + '\n')
        fnew.close()
        shutil.move(index_file_new, index_file)
    else:
        print("must name a file")
        sys.exit(2)

if __name__ == "__main__":
    main()
    print("NOTE: ought to check for hash collisions (FIXME)")
