#!/usr/bin/env python3
import sys
import hashlib
import os
import shutil


def main():
    archive = "~/archive"
    if len(sys.argv) != 2 and len(sys.argv) != 3:
        print("usage: a file [\"comment\"]")
        sys.exit(2)
    if len(sys.argv) > 1:
        filename = sys.argv[1]
        name, extension = os.path.splitext(filename)
        #print("filename  %s" % filename)
        #print("name      %s" % name)
        #print("extension %s" % extension)
        if (len(sys.argv) == 3):
            comment = sys.argv[2]
        else:
            comment = ""
        cwd = os.getcwd()
        path = cwd + "/" + filename
        hash = str(hashlib.sha1(str(path).encode('utf-8')).hexdigest())[:6]
        destination = archive + "/" + str(hash) + extension
        print("PATH:        %s" % path)
        print("HASH:        %s" % hash)
        print("COMMENT:     %s" % comment)
        print("DESTINATION: %s" % destination)
    else:
        print("must name a file")
        sys.exit(2)

if __name__ == "__main__":
    main()
